name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 增加超时时间到30分钟

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'
        registry-url: 'https://registry.npmmirror.com'

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Build the Docker image
      run: |
        export DOCKER_BUILDKIT=1
        docker build . --file Dockerfile --tag my-image-name:$(date +%s) \
          --build-arg proxy=https://registry.npmmirror.com \
          --build-arg base_url=${{ env.NEXT_PUBLIC_BASE_URL }}
      env:
        NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Push Docker image
      if: github.event_name == 'push'
      run: docker push my-image-name:$(date +%s)
