name: Docker Image CI
#注释即可关闭自动工作流
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 增加超时时间到30分钟

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'
        registry-url: 'https://registry.npmmirror.com'

    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Set image tag
      id: set-image-tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        export DOCKER_BUILDKIT=1
        docker build . --file Dockerfile --tag my-image-name:${{ env.IMAGE_TAG }} \
          --build-arg proxy=https://registry.npmmirror.com \
          --build-arg base_url=${{ env.NEXT_PUBLIC_BASE_URL }}
      env:
        NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image
      if: github.event_name == 'push'
      run: docker push my-image-name:${{ env.IMAGE_TAG }}
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
